// Copies a fixed set of Lucide icon SVGs from the lucide-static devDependency
// into renderer/icons.js as inline markup, so the app never fetches or
// bundles icons at runtime - everything ships baked into the app already.
'use strict';
const fs = require('fs');
const path = require('path');

const ICONS = [
  'settings', 'sun', 'moon', 'image', 'pin', 'pin-off', 'tag', 'hash',
  'link', 'search', 'plus', 'trash-2', 'x', 'minimize-2', 'maximize-2', 'pencil', 'eye',
  'command', 'palette', 'folder-open', 'square-check', 'check', 'bell', 'triangle-alert'
];

const srcDir = path.join(__dirname, '..', 'node_modules', 'lucide-static', 'icons');
const outFile = path.join(__dirname, '..', 'renderer', 'icons.js');

const entries = ICONS.map((name) => {
  const raw = fs.readFileSync(path.join(srcDir, `${name}.svg`), 'utf8');
  const svg = raw.replace(/<!--[\s\S]*?-->\s*/g, '').trim();
  return `  ${JSON.stringify(name)}: ${JSON.stringify(svg)}`;
});

const banner = '// Generated by scripts/sync-icons.js - do not edit by hand.\n' +
  '// Source: lucide-static (https://lucide.dev), bundled offline.\n';

fs.writeFileSync(
  outFile,
  `${banner}window.KEEPNOTES_ICONS = {\n${entries.join(',\n')}\n};\n`,
  'utf8'
);

console.log(`Wrote ${ICONS.length} icons to ${path.relative(process.cwd(), outFile)}`);
